### ISSUE TITLE
Computer Only Plays One Round

### ISSUE THREAD

**Issue by alexanderepstein** [DavidWigley/Digital-Logic-Final-Project#3]
The output as of now looks like this it works for the first turn. The user goes middle right and the computer goes bottom right. Then the user goes middle left and the computer doesn't respond. It did not even respond to the next input where the user goes top left.
If i had to guess there is some conditional preventing the computer from inserting an x or the x it decides to choose happens to be the same for some reason (maybe parameters aren't reset) but i am not seeing it.

           0           0           0
           0           0           0
           0           0           0
 

 
 
           0           0           0
           0           0           1
           0           0           0
 
 
 
 
           0           0           0
           0           0           1
           0           0           2
 

 
           0           0           0
           1           0           1
           0           0           2
 
 
 
 
           1           0           0
           1           0           1
           0           0           2

**Comment by DavidWigley** [comment]
I see what you're saying. Will look into Wednesday after the test (hopefully). Going to use most of the time tomorrow and Wednesday to study then will try to resolve.

**Comment by alexanderepstein** [comment]
I started fixing it a little bit more with the last push to github but now some other problems arise.





           0           0           0
           0           0           0
           0           0           0


 



 
           0           0           0
           0           0           1
           0           0           0
 
 
 
 
# X inserted, MyPriority was:           1
           0           0           0
           0           2           1
           0           0           0
 
 
 
 
           0           0           0
           0           2           1
           0           0           1
 
 
 
 
#  X inserted, MyPriority was:           2
           0           0           0
           1           2           1
           0           0           1
 
 
 
 
# X inserted, MyPriority was:           2
           1           0           0
           1           2           1
           0           0           1
 
 

 
# X inserted, MyPriority was:           3
           2           0           0
           1           2           1
           0           0           1

**Comment by DavidWigley** [comment]
Fairly certain this was fixed
https://github.com/DavidWigley/Digital-Logic-Final-Project/commit/14ae142675b029e8416a35c4a7f902991c3a2e9c

Was lots of logic checking errors with columns and rows, particularly the third column. Some insertion problems were fixed as well.
