### ISSUE TITLE
Block trigger signal after win

### ISSUE THREAD

**Issue by DavidWigley** [DavidWigley/Digital-Logic-Final-Project#5]
In the Logisim version, only one game is able to be played.

Anyways to force this condition we can run and OR from the CPU and USER win conditions then run an XOR with that and the trigger. Basically if someone has won I wont allow new signals.

Of course this does not account for the case of a tie.

**Comment by alexanderepstein** [comment]
This should have been solved in my last Logisim push TTT_Flamingo is it not?

**Comment by DavidWigley** [comment]
Apologies was testing Epsilon. Naming convention is strange :)

**Comment by DavidWigley** [comment]
@alexanderepstein You're correct. This is implemented. Closing
